MEANBenchmark:
  shape_desc: M, N, K
  shapes:
  - [512, 1, 1, null]
  - [1024, 1, 1, null]
  - [1536, 1, 1, null]
  - [2048, 1, 1, null]
  - [2560, 1, 1, null]
  - [3072, 1, 1, null]
  - [3584, 1, 1, null]
  - [4096, 1, 1, null]
  - [4608, 1, 1, null]
  - [5120, 1, 1, null]
  - [5632, 1, 1, null]
  - [6144, 1, 1, null]
  - [6656, 1, 1, null]
  - [7168, 1, 1, null]
  - [7680, 1, 1, null]
  - [8192, 1, 1, null]
